"""add auth accounts and student dimension scores

Revision ID: cacc9d9ba52d
Revises: e8b2f9876f6c
Create Date: 2026-09-23 00:13:36.052235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cacc9d9ba52d'
down_revision: Union[str, Sequence[str], None] = 'e8b2f9876f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('student_dimension_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_dimension_scores_created_at'), 'student_dimension_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_student_dimension_scores_dimension'), 'student_dimension_scores', ['dimension'], unique=False)
    op.create_index(op.f('ix_student_dimension_scores_session_id'), 'student_dimension_scores', ['session_id'], unique=False)
    op.create_index(op.f('ix_student_dimension_scores_student_id'), 'student_dimension_scores', ['student_id'], unique=False)
    op.add_column('students', sa.Column('roll_number', sa.String(length=32), nullable=False))
    op.add_column('students', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_students_roll_number'), 'students', ['roll_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_roll_number'), table_name='students')
    op.drop_column('students', 'password_hash')
    op.drop_column('students', 'roll_number')
    op.drop_index(op.f('ix_student_dimension_scores_student_id'), table_name='student_dimension_scores')
    op.drop_index(op.f('ix_student_dimension_scores_session_id'), table_name='student_dimension_scores')
    op.drop_index(op.f('ix_student_dimension_scores_dimension'), table_name='student_dimension_scores')
    op.drop_index(op.f('ix_student_dimension_scores_created_at'), table_name='student_dimension_scores')
    op.drop_table('student_dimension_scores')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
