"""add student department/year and profile resume

Revision ID: d94bce8b5321
Revises: cacc9d9ba52d
Create Date: 2026-09-23 00:43:25.111308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94bce8b5321'
down_revision: Union[str, Sequence[str], None] = 'cacc9d9ba52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_resumes_student_id'), 'student_resumes', ['student_id'], unique=True)
    op.add_column('students', sa.Column('department', sa.String(length=32), nullable=True))
    op.add_column('students', sa.Column('year', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'year')
    op.drop_column('students', 'department')
    op.drop_index(op.f('ix_student_resumes_student_id'), table_name='student_resumes')
    op.drop_table('student_resumes')
    # ### end Alembic commands ###
