ASSESSMENT_CATALOG = [
    {
        "id": "hr", "title": "HR Interview", "kind": "THE OPENING ROUND", "icon": "users",
        "description": "The questions every panel opens with. Judged on whether you sound prepared rather than rehearsed.",
        "status": "ready", "measures": ["Fluency", "Clarity", "Conciseness"], "soon_reason": None,
        "questions": [
            {"prompt": "Tell me about yourself.", "guidance": "Present → past → why you are here. Skip the childhood.", "target": 90},
            {"prompt": "Why this role, and why now?", "guidance": "Name something specific about the work, not the brand.", "target": 75},
            {"prompt": "What is your biggest strength? Give one example.", "guidance": "One strength, one story, one result.", "target": 75},
            {"prompt": "Where do you see yourself in three years?", "guidance": "A direction beats a job title.", "target": 60},
            {"prompt": "Do you have any questions for us?", "guidance": "Ask about the work, the team, or how success is measured.", "target": 45},
        ],
    },
    {
        "id": "technical", "title": "Technical Interview", "kind": "EXPLAIN YOUR WORK", "icon": "layers",
        "description": "Talk through what you built and why. Tests whether you can make a technical decision legible to someone who was not there.",
        "status": "ready", "measures": ["Clarity", "Structure", "Vocabulary"], "soon_reason": None,
        "questions": [
            {"prompt": "Walk me through a project you built end to end.", "guidance": "Problem → what you chose → what it cost you.", "target": 120},
            {"prompt": "What was the hardest bug you have debugged? How did you find it?", "guidance": "The method matters more than the bug.", "target": 90},
            {"prompt": "Explain a technical concept you know well to someone non-technical.", "guidance": "Plain words first. Analogy second. Jargon last, if at all.", "target": 60},
            {"prompt": "Describe a trade-off you made and what you gave up.", "guidance": "A real trade-off has a loser. Name it.", "target": 90},
            {"prompt": "What would you build differently if you started again?", "guidance": "Specific regret, specific reason.", "target": 75},
        ],
    },
    {
        "id": "behavioral", "title": "Behavioural Round", "kind": "STAR FRAMEWORK", "icon": "spark",
        "description": "Situation, Task, Action, Result. The round where good stories get lost in setup and never reach the outcome.",
        "status": "ready", "measures": ["Structure", "Conciseness", "Clarity"], "soon_reason": None,
        "questions": [
            {"prompt": "Tell me about a time you disagreed with a teammate.", "guidance": "Situation → Task → Action → Result. Land the Result.", "target": 105},
            {"prompt": "Describe a deadline you missed. What happened next?", "guidance": "Own it early, spend your time on the recovery.", "target": 105},
            {"prompt": "Give an example of a time you led without being in charge.", "guidance": "Influence, not authority. What did you actually do?", "target": 105},
            {"prompt": "Tell me about feedback that was hard to hear.", "guidance": "What you changed matters more than how it felt.", "target": 90},
            {"prompt": "Describe a time you had to learn something fast.", "guidance": "Method, then evidence it worked.", "target": 90},
        ],
    },
    {
        "id": "placement", "title": "Placement Mock", "kind": "FULL LOOP", "icon": "briefcase",
        "description": "A mixed round that moves between HR, technical and behavioural without warning — closest to a real campus loop.",
        "status": "ready", "measures": ["Fluency", "Clarity", "Structure", "Conciseness", "Vocabulary"], "soon_reason": None,
        "questions": [
            {"prompt": "Tell me about yourself.", "guidance": "Ninety seconds. Present, past, why here.", "target": 90},
            {"prompt": "Walk me through the project you are proudest of.", "guidance": "Your contribution, not the team's.", "target": 120},
            {"prompt": "Tell me about a time something went wrong on that project.", "guidance": "STAR. Do not stop before the Result.", "target": 105},
            {"prompt": "Why should we pick you over someone with the same marks?", "guidance": "Evidence, not adjectives.", "target": 75},
            {"prompt": "Explain your final-year work to a non-technical interviewer.", "guidance": "No jargon without a plain-English setup.", "target": 90},
            {"prompt": "Where do you want to be by the end of your first year here?", "guidance": "Concrete and modest beats grand and vague.", "target": 60},
        ],
    },
    {
        "id": "impromptu", "title": "Impromptu Speaking", "kind": "NO PREPARATION", "icon": "clock",
        "description": "A topic you have not seen, sixty seconds to answer. The round that exposes filler words and thinking-out-loud habits.",
        "status": "ready", "measures": ["Fluency", "Conciseness"], "soon_reason": None,
        "questions": [
            {"prompt": "Should every student learn to code? Take a side.", "guidance": "Pick a side in the first sentence.", "target": 60},
            {"prompt": "What is one thing your college should change tomorrow?", "guidance": "One thing. One reason. One outcome.", "target": 60},
            {"prompt": "Is remote work better for early-career engineers?", "guidance": "Commit, then justify. Do not hedge both ways.", "target": 60},
            {"prompt": "Describe your hometown to someone who will never visit.", "guidance": "Three concrete details beat ten adjectives.", "target": 60},
            {"prompt": "What is the most useful thing you learned outside a classroom?", "guidance": "A story, then the lesson. Not the reverse.", "target": 60},
        ],
    },
    {
        "id": "presentation", "title": "Presentation Simulation", "kind": "TO A PANEL", "icon": "trend",
        "description": "Open, structure and close a short talk. Scored on whether a listener could repeat your point afterwards.",
        "status": "ready", "measures": ["Structure", "Clarity", "Vocabulary"], "soon_reason": None,
        "questions": [
            {"prompt": "Open your project presentation. First thirty seconds only.", "guidance": "Hook, then what it is, then why it matters.", "target": 30},
            {"prompt": "Present your approach and the alternatives you rejected.", "guidance": "Signpost it: three options, I chose the second.", "target": 120},
            {"prompt": "Present your results to a room that has not seen the data.", "guidance": "The headline number first, the method after.", "target": 90},
            {"prompt": "A panellist interrupts: why should we believe this? Answer.", "guidance": "Answer the question asked, then return to your thread.", "target": 60},
            {"prompt": "Close the presentation. Last thirty seconds.", "guidance": "Restate the one thing you want remembered.", "target": 30},
        ],
    },
    {
        "id": "gd", "title": "Group Discussion", "kind": "MULTI-SPEAKER", "icon": "messageSquare",
        "description": "A placement GD room with AI peers. Needs speaker separation to score floor-share and interruption timing.",
        "status": "soon", "measures": ["Fluency", "Clarity"], "soon_reason": "Needs speaker diarisation — PRD phase 2.", "questions": [],
    },
    {
        "id": "workplace", "title": "Workplace Scenarios", "kind": "ON THE JOB", "icon": "briefcase",
        "description": "Client meetings, negotiations and difficult conversations — communication after you are hired, not to get hired.",
        "status": "soon", "measures": ["Clarity", "Structure"], "soon_reason": "Corporate simulation — PRD phase 5.", "questions": [],
    },
]
